
server:
  port: 8080
#  servlet:
#    context-path: /bears

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    username: root
    password: Subhana@2020
    url: jdbc:mysql://34.130.13.72:3306/reimb

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  spring.mail.host : smtp.gmail.com
  spring.mail.port : 587
  spring.mail.username : anjalithakar33@gmail.com
  spring.mail.password : Subhana@1711
  spring.mail.properties.mail.smtp.auth : true
  spring.mail.properties.mail.smtp.starttls.enable : true